version: "2.15.1"
services:
  database:
    image: postgres:13
    container_name: database
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: task
    ports:
      - "5432:5432"

  backend:
    build: .
    depends_on:
      - database
    container_name: backend